# (PART) I. Introducción a la programación de computadoras {-}

# Pensamiento computacional

## Resumen
El pensamiento computacional es un enfoque para la resolución de problemas basado en conceptos y métodos de las ciencias de la computación. Los principios fundamentales del pensamiento computacional son:

- **Descomposición**: división de un problema en subproblemas más pequeños.
- **Reconocimiento de patrones**: búsqueda de similitudes en los problemas.
- **Abstracción**: identificación de la información que se necesita y filtrado de la que no se necesita para resolver un problema.
- **Algoritmos**: descripción, paso por paso, de la solución a un problema.

## Diapositivas
[**Introducción al pensamiento computacional (diapositivas)**](https://gf0604-procesamientodatosgeograficos.github.io/2022-i-introduccion-pensamiento-computacional/)

## Recursos de interés

Harvard University. (2022). *CS50’s Introduction to Computer Science*. EdX. https://www.edx.org/course/introduction-computer-science-harvardx-cs50x

Wing, J. M. (2006). Computational thinking. *Communications of the ACM, 49*(3), 33-35. https://doi.org/10.1145/1118178.1118215. Disponible en https://www.cs.cmu.edu/~15110-s13/Wing06-ct.pdf.